### ISSUE TITLE
UX: If invalid 'table.include.list' is provided, graceful message should be given in response

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/debezium-connector-yugabytedb#37]
Try to run POST command with wrong 'table.include.list'

Observation:
It returns: curl: (52) Empty reply from server

Trying again, results in curl: (56) Recv failure: Connection reset by peer

Connector service went down

Expectation:
Graceful message saying provided 'table.include.list' couldn't be found in database or so, could be displayed in response. As of now, I couldn't find in docker logs of connector as well, but it is better to provide in response even if we give in logs in terms of UX.

**Comment by vaibhav-yb** [comment]
@shamanthchandra-yb I believe you got this one resolved in the newer release i.e. `1.7.0.12-BETA`, right? Can you please close this issue if resolved?

**Comment by vaibhav-yb** [comment]
Closing since the issue has been resolved.
