### ISSUE TITLE
[1.7.0.12-BETA] table.include.list is made mandatory in yugabyte debezium connector instead of optional 

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/debezium-connector-yugabytedb#46]
table.include.list is optional in previous versions (I have checked in quay.io/yugabyte/debezium-connector:1.3.7-BETA)

where as '[quay.io/yugabyte/debezium-connector:1.7.0.12-BETA](http://quay.io/yugabyte/debezium-connector:1.7.0.12-BETA)'

has is mandatory. Thus we see below exception:

`AssertionError: Failed to add connector stream. res.reason='Internal Server Error' res.content=b'{"error_code":500,"message":"The table.include.list is empty, please provide a list of tables to get the changes from"}'`

Drawbacks of this approach:
1. Different behaviour with upstream (default debezium behaviour)
2. Removes support for having CDC enabled for all tables in database.
3. When upgraded, compatibility issues will be seen.

**Comment by vaibhav-yb** [comment]
Closing this issue because the include list was made mandatory because of usability requests.
