### ISSUE TITLE
Message to be logged in connector log to indicate its up

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/debezium-connector-yugabytedb#58]
As per discussion with @vaibhav-yb , a log message to be added to indicate connector is up. This will help in testing correctly, so that workloads can be run after connector is up.

**Comment by vaibhav-yb** [comment]
As per recent changes, we have added one log line, it says:
```
Beginning to poll the changes from the server
```

However, do note that this log line comes up for each task we have for the connector so one would need to keep that in mind while working with this.
