### ISSUE TITLE
Colocated + CDC: Debezium Connector shows quite a few message like 'COMMIT record encountered without a preceding BEGIN record'  

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/debezium-connector-yugabytedb#67]
Kafka connect log shows:

WARN   YugabyteDB|db_cdc|streaming  Error while trying to get the changes from the server; will attempt retry 1 of 5 after 60000 milli-seconds. Exception message: COMMIT record encountered without a preceding BEGIN record   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]

As per discussion with @vaibhav-yb , this should be released with whatever next version released. Just having this placeholder from QA to track it.

**Comment by vaibhav-yb** [comment]
This has been fixed and the changes are not landed in main branch.
