### ISSUE TITLE
[CDC + Improvement] Need some log after bootrapping all tablets of table

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/debezium-connector-yugabytedb#70]
For automation, instead of putting static wait, its better if some log saying in connector log:

"Bootstrap completed for table <table_name>"

**Comment by vrajat** [comment]
You can also query prometheus. There are a couple of metrics that track snapshot progress - snapshot_total_tables and snapshot_completed_tables

**Comment by vaibhav-yb** [comment]
Closing this as it's the duplicate for issue #58
